updater: true
no-permission: "&cYou do not have permission to use this command."

hide-inventory:
  enabled: true
  whitelist:
    - "minecraft:iron_sword"
  blacklist: []
  flags-to-hide:
    - HIDE_ENCHANTS
    - HIDE_ATTRIBUTES
    - HIDE_UNBREAKABLE
    - HIDE_ADDITIONAL_TOOLTIP
    - HIDE_PLACED_ON
    - HIDE_DYE
    - HIDE_STORED_ENCHANTS
    - HIDE_ITEM_SPECIFICS

hidden-guis:
  server-selector:
    title: "&8Server Selector"
    whitelist: []
    blacklist:
      - "minecraft:iron_sword"
    flags-to-hide:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
      - HIDE_UNBREAKABLE
      - HIDE_ADDITIONAL_TOOLTIP
      - HIDE_PLACED_ON
      - HIDE_DYE
      - HIDE_STORED_ENCHANTS
      - HIDE_ITEM_SPECIFICS
  cosmetics:
    title: "&#c726e0Cosmetics"
    whitelist: []
    blacklist: []
    flags-to-hide:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
      - HIDE_UNBREAKABLE
