name: AllFlagsHidder
main: org.wcrazy.AllFlagsHidder
version: 1.0.2
api-version: 1.21
depend: [ProtocolLib]
commands:
  allflagshidder:
    description: Commands for AllFlagsHidder
    usage: /<command> reload
    aliases: [afh]
